# Настройки сервера
server.port=8080
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5545/cinema
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# spring.jpa.show-sql=false
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=misha41526@gmail.com
spring.mail.password=aqsi qtao kedb fffi 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true